spring:
  ai:
    ollama:
      base-url: http://localhost:11434/
      model: llama3.2

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9090/eureka
server:
  port: 8084

management:
  endpoints:
    web:
      exposure:
        include: "*"