eureka:
  client:
    service-url:
      defaultZone: http://localhost:9090/eureka
server:
  port: 8084
spring:
  application:
    name: Ai-Bot-Service
  huggingface:
    apiUrl: https://api-inference.huggingface.co/models/gpt2
    apiToken: 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

management:
  endpoints:
    web:
      exposure:
        include: "*"
