eureka:
    client:
        service-url:
            defaultZone: http://localhost:9090/eureka
server:
    port: 8085
spring:
    application:
        name: Employee-Service
    data:
        mongodb:
            uri: mongodb://localhost:27017/Employee-DB
    ai:
        mcp:
            server:
                name: webflux-mcp-server
                version: 1.0.0
                type: ASYNC
                sse-message-endpoint: /mcp/messages
