eureka:
    client:
        service-url:
            defaultZone: http://localhost:9090/eureka
server:
    port: 8085
spring:
    application:
        name: Employee-Service
    data:
        mongodb:
            uri: mongodb://localhost:27017/Employee-DB
